# Generated by Django 4.2.5 on 2023-09-17 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_about_denuncia_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='created',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated',
        ),
    ]
