# Generated by Django 4.2.5 on 2023-09-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_about_created_remove_about_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
