# Generated by Django 4.2.5 on 2023-09-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(max_length=500, null=True, upload_to=''),
        ),
    ]
